# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 00:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(max_length=50)),
                ('d_id', models.CharField(max_length=12)),
                ('district', models.CharField(max_length=2)),
                ('startcong', models.CharField(max_length=10)),
                ('endcong', models.CharField(max_length=10)),
                ('districtsi', models.CharField(max_length=32)),
                ('county', models.CharField(max_length=32)),
                ('page', models.CharField(max_length=32)),
                ('law', models.CharField(max_length=32)),
                ('note', models.CharField(max_length=32)),
                ('bestdec', models.CharField(max_length=32)),
                ('finalnote', models.CharField(max_length=26)),
                ('rnote', models.CharField(max_length=32)),
                ('lastchange', models.CharField(max_length=29)),
                ('fromcounty', models.CharField(max_length=2)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269)),
            ],
        ),
    ]
